### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by alexmojaki** [alexmojaki/futurecoder#123]
@matan-h has pointed out that futurecoder doesn't run on Windows. I don't use Windows so this is not easy for me to deal with.

I imagine that it's possible to run on Windows using Docker (right?) but that's not good enough. Developers should be able to run directly on their machine if they prefer that workflow (as I do). We also need Windows compatibility if we want to make an easy to install desktop program as described in #89.

First of all, what exactly goes wrong when running on Windows? I'm sure you can't run `setup.sh` but it should be easy to emulate the steps within: install poetry, run `poetry install`, run some manage commands. But I assume there are other problems, I haven't paid much attention to OS compatibility.

**Comment by spamegg1** [comment]
I've started investigating.

It seems not possible to use Docker. Apparently my CPU does not have SLAT (Second Level Address Translation) capabilities needed to run Docker on Windows. Windows 10 won't let me install the Hyper-V Hypervisor because of this. In addition Docker needs a lot of other things, like WSL2. Also it requires Windows 10 Pro (there is some other complicated method for Windows 10 Home).

Docker is installed, but it's not really working. `docker-compose up` fails as a result with: 
```
Traceback (most recent call last):                                                                                                                              
File "site-packages\docker\api\client.py", line 205, in _retrieve_server_version                                                                              
File "site-packages\docker\api\daemon.py", line 181, in version                                                                                               
File "site-packages\docker\utils\decorators.py", line 46, in inner                                                                                            
File "site-packages\docker\api\client.py", line 228, in _get                                                                                                  
File "site-packages\requests\sessions.py", line 543, in get                                                                                                   
File "site-packages\requests\sessions.py", line 530, in request                                                                                               
File "site-packages\requests\sessions.py", line 643, in send                                                                                                  
File "site-packages\requests\adapters.py", line 449, in send                                                                                                  
File "site-packages\urllib3\connectionpool.py", line 677, in urlopen                                                                                          
File "site-packages\urllib3\connectionpool.py", line 392, in _make_request                                                                                    
File "http\client.py", line 1244, in request                                                                                                                  
File "http\client.py", line 1290, in _send_request                                                                                                            
File "http\client.py", line 1239, in endheaders                                                                                                               
File "http\client.py", line 1026, in _send_output                                                                                                             
File "http\client.py", line 966, in send                                                                                                                      
File "site-packages\docker\transport\npipeconn.py", line 32, in connect                                                                                       
File "site-packages\docker\transport\npipesocket.py", line 23, in wrapped                                                                                     
File "site-packages\docker\transport\npipesocket.py", line 72, in connect                                                                                     
File "site-packages\docker\transport\npipesocket.py", line 59, in connect                                                                                   
pywintypes.error: (2, 'CreateFile', 'The system cannot find the file specified.') 
```

`poetry install` in the `backend` folder installs everything, except it fails at `• Installing pangocairocffi (0.3.2) ` with an `EnvCommandError`. It says
```
File "C:\Users\spamegg\AppData\Local\pypoetry\Cache\virtualenvs\book-vfm7nxrT-py3.8\lib\site-packages\pangocffi\__init__.py", line 16, in _dlopen                  
raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))                                                                                
OSError: dlopen() failed to load a library: pango / pango-1 / pango-1.0 / pango-1.0-0
```
Apparently this is a known thing that `manim` [claims to fix in its latest version](https://docs.manim.community/en/latest/installation/troubleshooting.html#windows-oserror-dlopen-failed-to-load-a-library-pango)
I tried changing `pangocairocffi` version in the `poetry.lock` file but it gets into resolve conflicts with `manimce`.
Will keep investigating.

**Comment by alexmojaki** [comment]
Thanks. I've removed the manim dependency, it was only for making the video.

**Comment by spamegg1** [comment]
OK, `poetry install` succeeded!

I changed `manimce` version to `0.1.1`, its `pangocairocffi` dependency to `>=0.6.0` and `pangocairocffi` itself to `0.6.0` and it worked.

**Comment by spamegg1** [comment]
Ah, I didn't see your comment!

**Comment by spamegg1** [comment]
OK... next up is `poetry run ./manage.py migrate`                                                                                                                                                                                      

```
OSError                                                                                                                                                                                                                                                                                                                     
[WinError 193] %1 is not a valid Win32 application                                                                                                                                                                                                                                                                          
at c:\program files\python38\lib\subprocess.py:1307 in _execute_child                                                                                             
1303│             sys.audit("subprocess.Popen", executable, args, cwd, env)                                                                                   
1304│                                                                                                                                                         
1305│             # Start the process                                                                                                                         
1306│             try:                                                                                                                                      
→ 1307│                 hp, ht, pid, tid = _winapi.CreateProcess(executable, args,                                                                              
1308│                                          # no special security                                                                                          
1309│                                          None, None,                                                                                                    
1310│                                          int(not close_fds),                                                                                            
1311│                                          creationflags, 
```

**Comment by alexmojaki** [comment]
Try `python manage.py` instead of `./manage.py`.

**Comment by spamegg1** [comment]
```
poetry run python manage.py migrate
** On entry to DGEBAL parameter number  3 had an illegal value                                                                                                
** On entry to DGEHRD  parameter number  2 had an illegal value                                                                                               
** On entry to DORGHR DORGQR parameter number  2 had an illegal value                                                                                         
** On entry to DHSEQR parameter number  4 had an illegal value                                                                                               
Traceback (most recent call last):                                                                                                                              
File "manage.py", line 28, in <module>                                                                                                                          
main()                                                                                                                                                      
File "manage.py", line 24, in main                                                                                                                              
execute_from_command_line(sys.argv)                                                                                                                         
File "C:\Users\spamegg\AppData\Local\pypoetry\Cache\virtualenvs\book-vfm7nxrT-py3.8\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line                                                                                                                                                
utility.execute()                                                                                                                                           
File "C:\Users\spamegg\AppData\Local\pypoetry\Cache\virtualenvs\book-vfm7nxrT-py3.8\lib\site-packages\django\core\management\__init__.py", line 357, in execute    
django.setup()                                                                                                                                              
File "C:\Users\spamegg\AppData\Local\pypoetry\Cache\virtualenvs\book-vfm7nxrT-py3.8\lib\site-packages\django\__init__.py", line 24, in setup                       
apps.populate(settings.INSTALLED_APPS)                                                                                                                      
File "C:\Users\spamegg\AppData\Local\pypoetry\Cache\virtualenvs\book-vfm7nxrT-py3.8\lib\site-packages\django\apps\registry.py", line 114, in populate              
app_config.import_models()                                                                                                                                  
File "C:\Users\spamegg\AppData\Local\pypoetry\Cache\virtualenvs\book-vfm7nxrT-py3.8\lib\site-packages\django\apps\config.py", line 211, in import_models           
self.models_module = import_module(models_module_name)                                                                                                      
File "c:\program files\python38\lib\importlib\__init__.py", line 127, in import_module                                                                          
return _bootstrap._gcd_import(name[level:], package, level)                                                                                                 
File "<frozen importlib._bootstrap>", line 1014, in _gcd_import                                                                                               
File "<frozen importlib._bootstrap>", line 991, in _find_and_load                                                                                             
File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked                                                                                    
File "<frozen importlib._bootstrap>", line 671, in _load_unlocked                                                                                             
File "<frozen importlib._bootstrap_external>", line 783, in exec_module                                                                                       
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                                                                  
File "C:\Users\spamegg\Desktop\futurecoder\backend\main\models.py", line 4, in <module>                                                                            
from main.text import page_slugs_list, pages                                                                                                                
File "C:\Users\spamegg\Desktop\futurecoder\backend\main\text.py", line 23, in <module>                                                                             
from main.exercises import (                                                                                                                                
    File "C:\Users\spamegg\Desktop\futurecoder\backend\main\exercises.py", line 11, in <module>                                                                        
    from main.utils import format_exception_string, returns_stdout                                                                                              
    File "C:\Users\spamegg\Desktop\futurecoder\backend\main\utils\__init__.py", line 26, in <module>                                                                   
    site_packages = strip_required_suffix(pygments.__file__, "pygments/__init__.py")                                                                            
    File "C:\Users\spamegg\AppData\Local\pypoetry\Cache\virtualenvs\book-vfm7nxrT-py3.8\lib\site-packages\littleutils\__init__.py", line 306, in strip_required_suffix                                                                                                                                                               
    raise AssertionError('String ends with %r, not %r' % (string[-len(suffix):], suffix))                                                                     
    AssertionError: String ends with 'pygments\\__init__.py', not 'pygments/__init__.py'
```

**Comment by alexmojaki** [comment]
I'm sure you can fix that. Use `os.path.sep`.

**Comment by spamegg1** [comment]
I changed `backend/main/utils/__init__.py` line 26 to: 
```python
site_packages = strip_required_suffix(pygments.__file__, f"pygments{os.path.sep}__init__.py")
```
I changed `backend/main/workers/limits.py` where I moved `import resource` inside the function `set_limits` like so:
```python
def set_limits():
    import resource
    destroy_dangerous_functions()
```
also set environment variable `SET_LIMITS` to `false` (on Windows this can be done from: System Properties/Advanced/Environment Variables. After that it can be viewed in PowerShell with `dir env:`)
This way `poetry run python manage.py migrate` worked. `poetry run python manage.py init_db` also works without problems.

**Comment by spamegg1** [comment]
BEFORE `npm install` in the `frontend` folder, another command is needed: `npm install --global windows-build-tools` to take care of `npm`s Python2 dependencies and other stuff (don't manually install Python2 and add it to PATH, it doesn't work and it will mess up `python.exe` to point to Python2).

**Comment by spamegg1** [comment]
Followed the instructions [here](https://github.com/coreybutler/nvm-windows) to install `nvm` for Windows.
Removed all `node` versions.
Installed `node 12.13.0` using `nvm`. 
Activated it with `nvm use 12.13.0` and made sure to open a new Powershell window and verify with `node -v`.
Did `npm install --global windows-build-tools`.
Made a fresh clone of futurecoder.
Then did `npm install` in the frontend folder.
`npm list http-proxy-middleware` reports:
```
frontend@0.1.0 C:\Users\spamegg\Desktop\futurecoder\frontend
+-- http-proxy-middleware@1.0.6                                                                                                                              
   `-- react-scripts@3.2.0                                                                                                                                        
      `-- webpack-dev-server@3.2.1                                                                                                                                   
         `-- http-proxy-middleware@0.19.1 
```
So obviously I still get the `proxy not a function` error.
Gonna try with other `node` versions next.

**Comment by spamegg1** [comment]
OK, all that's left is to update the instructions. Windows instructions can be something like this (not too sure about the level of detail):

### On Windows:

The instructions below require a Powershell window with "Run as Administrator." 

1. Fork the repository, and clone your fork.
2. Create an environment variable named `SET_LIMITS` and set its value to `false`.
3. Install `poetry` by following the instructions [here](https://python-poetry.org/docs/#windows-powershell-install-instructions).
4. In the `backend` folder:
   1. Ensure the `python` command points to Python 3.8.
   2. Run `poetry install` to install the dependencies.
   3. Run `poetry run python manage.py migrate` to run migrations.
   4. Run `poetry run python manage.py init_db` to create a database and a user.
   5. Run the backend development server with `poetry run python manage.py runserver`.
5. In the `frontend` folder:
   1. Ensure you have recent versions of `node` and `npm`.
   2. Run `npm install --global windows-build-tools`.
   3. Run `npm ci` to download dependencies.
   4. Run `npm start` to start the frontend development server.

We can add a warning after Linux and Windows instructions about Firefox:

If you are using Firefox you might see a warning "Unhandled Rejection (SecurityError): The operation is insecure." You can click the X button to ignore it and continue testing. But the warning will come back whenever you go to another page. If you want to get rid of the warnings temporarily as you work, change the last line of the file `frontend/src/index.js` from `serviceWorker.unregister();` to `serviceWorker.register();`. Then restart the frontend server. (Remember to change it back before committing.)

**Comment by alexmojaki** [comment]
1. Let's stick to a single README for both platforms, there's not much difference. You can say "Windows only:" and "or on Windows..."
2. Does windows need the `\.`? Can you just run `setup.ps1`?
3. I would still recommend `poetry shell` so that users can do other things like run tests.
4. I forgot that bit about recent versions of node, that's a problem. Change it to node 12, pending #124 
5. Recommend `npm ci` and `python manage.py` on all platforms
6. I should probably understand this service worker thing better but for now try replacing the code with something like `try {unregister()} catch {register()}` and see if that works in all browsers. Then we don't need special instructions.

**Comment by spamegg1** [comment]
OK. 
Yes I meant the same README.
Windows needs the `.\` it's actually what Powershell told me to do in a very clever error message.
Yup, we should recommend `npm ci` on Linux too. 
I'll try and see if `poetry shell` works on Windows. Because it spawns a new shell inside the existing shell, I don't know if that plays nice with Powershell (probably does).
I'll test the service worker issue but I have my doubts; it seems a very Firefox specific thing. People report it happens in a fresh, blank, generic `create-react-app`.

**Comment by alexmojaki** [comment]
I don't just mean one file, I mean one set of instructions, inserting Windows mentions where needed.

**Comment by spamegg1** [comment]
I'm able to solve the security error issue in `serviceWorker.js`. I just added a `catch` but this is a hacky solution.

```javascript
export function unregister() {
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.ready.then(registration => {
      registration.unregister();
    }).catch(err => console.log("Service worker failed to unregister"));
  }
}
```

Another option is to simply switch to registering in `index.js`. It's supposed to [load faster and work better on mobile](https://create-react-app.dev/docs/making-a-progressive-web-app/#why-opt-in) that way, but it's supposed to make things harder to debug. This seems to be a matter of opinion people [argued](https://github.com/facebook/create-react-app/issues/2398) over about 4 years ago so they defaulted to unregistering, turning registration into an opt-in.

**Comment by alexmojaki** [comment]
1. Make a PR for the README
2. Make a separate issue/PR for the service workers
3. Confirm that everything is fine in the production site or when running docker-compose locally on all your browsers. If this is only a development issue I'm happy to delay it

**Comment by spamegg1** [comment]
OK I saw your message a bit late, ignore the branch `readme_serviceworker_unregister`
I'll do the Readme PR first with a different branch.

**Comment by alexmojaki** [comment]
Thanks for finding this. It says DOMException, I wonder if it's the same error? Maybe lots of things have that message?

Windows compatibility is done now so I'm closing this, please put this stuff in a new issue/PR.
